development: 
  AWS_ACCESS_KEY_ID: 'AKIAJWJLVTHKFAPVI52A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'eclat-homes-photos'
test: 
  AWS_ACCESS_KEY_ID: 'AKIAJWJLVTHKFAPVI52A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'eclat-homes-photos'
production: 
  AWS_ACCESS_KEY_ID: 'AKIAJWJLVTHKFAPVI52A'
  AWS_SECRET_ACCESS_KEY: '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'
  S3_BUCKET: 'eclat-homes-photos'

